### PR TITLE
Fixing init issue with app links

### PR DESCRIPTION
**Pull request by sojanpr**
Marking the app link in the intent as used once it is used for getting
deep link params in order to prevent providing wrong deep link data.

@aaustin

### CODE REVIEW

**Comment by sojanpr** [comment]
Tested and Review ready

**Comment by aaustin** [comment]
Does this still require onNewIntent and `singleTask` launch mode?

**Comment by sojanpr** [comment]
Unfortunately `onNewIntent` and  singleTask is still needed. With out which the case  of clicking a link when app is in background will not work properly

**Comment by aaustin** [comment]
:+1: looks great

**Pull request merged**
