### PR TITLE
Cleanup And Reorg

### PR DESCRIPTION
**Pull request by sojanpr**
PR for Clean Up and and some missing functionalities to the SDK
@aaustin @Sarkar @EvangelosG

### CODE REVIEW

**Comment by aaustin** [comment]
Looks like it's coming together nicely! Were there other items left on the backlog?

**Comment by aaustin** [comment]
As far as I can tell :+1: But if you add more here, let me know.

**Comment by sojanpr** [comment]
@Sarkar I tried with true but due to some AS lint issue it is aborting the makeJar. That why we ignore the Lint

**Comment by Sarkar** [comment]
makes sense. this looks good to me :+1:

**Comment by aaustin** [comment]
Looks good to me :+1:

**Pull request merged**
