### PR TITLE
Adding Styling option for list view

### PR DESCRIPTION
**Pull request by sojanpr**
Since share sheet is  a custom  component minimal styling is added to
the sheet. Builder now provides option to add custom styles.

@aaustin

### CODE REVIEW

**Comment by sojanpr** [comment]
Tested and Review reay

**Comment by aaustin** [comment]
Looks good - can you add an example to the testbed so that others can see how this is used?

**Comment by sojanpr** [comment]
Example added for setting custom style

**Comment by aaustin** [comment]
:+1:

**Pull request merged**
