### PR TITLE
Deprecating LoadActionCounts

### PR DESCRIPTION
**Pull request by sojanpr**
Deprecating LoadActionCounts and associated methods
@derrickstaten  @Sarkar @aaustin

### CODE REVIEW

**Comment by Sarkar** [comment]
@sojanpr can you also add this notice to https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L1274 and https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L1285

And then I'll add the alternatives to the README at the bottom of this page.

**Comment by sojanpr** [comment]
@Sarkar Added deprecation to getTotalActionCount() and getUniqueActionCount()

**Comment by aaustin** [comment]
:+1:

**Comment by Sarkar** [comment]
:+1:

**Pull request merged**
